### ISSUE TITLE
using rtl

### ISSUE THREAD

**Issue by fath1993** [omidheshmatinia/LiquidRadioButton#1]
hi.
i want to use this library but dont know how to use it in rtl mode. because i use arabic language and want to radio button appier in the right of my text.
thanks

**Comment by omidheshmatinia** [comment]
There is no need to do anything ! The library support RTL languages by default. @dj1372 
![photo_2018-01-20_21-50-40](https://user-images.githubusercontent.com/9485780/35186659-fb1d4966-fe2c-11e7-952e-f72b14d757cd.jpg)
